// Auto-generated. Do not edit!

// (in-package yolact_ros.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Segments = require('./Segments.js');

//-----------------------------------------------------------

class SegmentationResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.segments = null;
      this.id = null;
    }
    else {
      if (initObj.hasOwnProperty('segments')) {
        this.segments = initObj.segments
      }
      else {
        this.segments = new Segments();
      }
      if (initObj.hasOwnProperty('id')) {
        this.id = initObj.id
      }
      else {
        this.id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SegmentationResult
    // Serialize message field [segments]
    bufferOffset = Segments.serialize(obj.segments, buffer, bufferOffset);
    // Serialize message field [id]
    bufferOffset = _serializer.int32(obj.id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SegmentationResult
    let len;
    let data = new SegmentationResult(null);
    // Deserialize message field [segments]
    data.segments = Segments.deserialize(buffer, bufferOffset);
    // Deserialize message field [id]
    data.id = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Segments.getMessageSize(object.segments);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'yolact_ros/SegmentationResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd543f9c9ec050563814d51c52fe7fbc5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result definition
    yolact_ros/Segments segments
    int32 id
    
    
    ================================================================================
    MSG: yolact_ros/Segments
    Header header
    Header image_header
    Segment[] segments
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: yolact_ros/Segment
    string Class
    float64 probability
    int32 xmin
    int32 ymin
    int32 xmax
    int32 ymax
    int32[] x_masks
    int32[] y_masks
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SegmentationResult(null);
    if (msg.segments !== undefined) {
      resolved.segments = Segments.Resolve(msg.segments)
    }
    else {
      resolved.segments = new Segments()
    }

    if (msg.id !== undefined) {
      resolved.id = msg.id;
    }
    else {
      resolved.id = 0
    }

    return resolved;
    }
};

module.exports = SegmentationResult;
