// Generated by gencpp from file yolact_ros/Segment.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MESSAGE_SEGMENT_H
#define YOLACT_ROS_MESSAGE_SEGMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolact_ros
{
template <class ContainerAllocator>
struct Segment_
{
  typedef Segment_<ContainerAllocator> Type;

  Segment_()
    : Class()
    , probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , x_masks()
    , y_masks()  {
    }
  Segment_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , probability(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)
    , x_masks(_alloc)
    , y_masks(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef double _probability_type;
  _probability_type probability;

   typedef int32_t _xmin_type;
  _xmin_type xmin;

   typedef int32_t _ymin_type;
  _ymin_type ymin;

   typedef int32_t _xmax_type;
  _xmax_type xmax;

   typedef int32_t _ymax_type;
  _ymax_type ymax;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_masks_type;
  _x_masks_type x_masks;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_masks_type;
  _y_masks_type y_masks;





  typedef boost::shared_ptr< ::yolact_ros::Segment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros::Segment_<ContainerAllocator> const> ConstPtr;

}; // struct Segment_

typedef ::yolact_ros::Segment_<std::allocator<void> > Segment;

typedef boost::shared_ptr< ::yolact_ros::Segment > SegmentPtr;
typedef boost::shared_ptr< ::yolact_ros::Segment const> SegmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros::Segment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros::Segment_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yolact_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'yolact_ros': ['/home/kamba/catkin_ws/src/yolact_ros/yolact_ros/msg', '/home/kamba/catkin_ws/devel/share/yolact_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::Segment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::Segment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::Segment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::Segment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::Segment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::Segment_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b822283fe5533fac6ff98c2ac9b6f3e";
  }

  static const char* value(const ::yolact_ros::Segment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b822283fe5533faULL;
  static const uint64_t static_value2 = 0xc6ff98c2ac9b6f3eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros/Segment";
  }

  static const char* value(const ::yolact_ros::Segment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n\
float64 probability\n\
int32 xmin\n\
int32 ymin\n\
int32 xmax\n\
int32 ymax\n\
int32[] x_masks\n\
int32[] y_masks\n\
";
  }

  static const char* value(const ::yolact_ros::Segment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros::Segment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.probability);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
      stream.next(m.x_masks);
      stream.next(m.y_masks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Segment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros::Segment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros::Segment_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "xmin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ymax);
    s << indent << "x_masks[]" << std::endl;
    for (size_t i = 0; i < v.x_masks.size(); ++i)
    {
      s << indent << "  x_masks[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x_masks[i]);
    }
    s << indent << "y_masks[]" << std::endl;
    for (size_t i = 0; i < v.y_masks.size(); ++i)
    {
      s << indent << "  y_masks[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y_masks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MESSAGE_SEGMENT_H
