; Auto-generated. Do not edit!


(cl:in-package yolact_ros-msg)


;//! \htmlinclude SegmentationFeedback.msg.html

(cl:defclass <SegmentationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SegmentationFeedback (<SegmentationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SegmentationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SegmentationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name yolact_ros-msg:<SegmentationFeedback> is deprecated: use yolact_ros-msg:SegmentationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SegmentationFeedback>) ostream)
  "Serializes a message object of type '<SegmentationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SegmentationFeedback>) istream)
  "Deserializes a message object of type '<SegmentationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SegmentationFeedback>)))
  "Returns string type for a message object of type '<SegmentationFeedback>"
  "yolact_ros/SegmentationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SegmentationFeedback)))
  "Returns string type for a message object of type 'SegmentationFeedback"
  "yolact_ros/SegmentationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SegmentationFeedback>)))
  "Returns md5sum for a message object of type '<SegmentationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SegmentationFeedback)))
  "Returns md5sum for a message object of type 'SegmentationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SegmentationFeedback>)))
  "Returns full string definition for message of type '<SegmentationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SegmentationFeedback)))
  "Returns full string definition for message of type 'SegmentationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SegmentationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SegmentationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SegmentationFeedback
))
