// Generated by gencpp from file yolact_ros/SegmentationResult.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MESSAGE_SEGMENTATIONRESULT_H
#define YOLACT_ROS_MESSAGE_SEGMENTATIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolact_ros/Segments.h>

namespace yolact_ros
{
template <class ContainerAllocator>
struct SegmentationResult_
{
  typedef SegmentationResult_<ContainerAllocator> Type;

  SegmentationResult_()
    : segments()
    , id(0)  {
    }
  SegmentationResult_(const ContainerAllocator& _alloc)
    : segments(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::yolact_ros::Segments_<ContainerAllocator>  _segments_type;
  _segments_type segments;

   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::yolact_ros::SegmentationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros::SegmentationResult_<ContainerAllocator> const> ConstPtr;

}; // struct SegmentationResult_

typedef ::yolact_ros::SegmentationResult_<std::allocator<void> > SegmentationResult;

typedef boost::shared_ptr< ::yolact_ros::SegmentationResult > SegmentationResultPtr;
typedef boost::shared_ptr< ::yolact_ros::SegmentationResult const> SegmentationResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros::SegmentationResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros::SegmentationResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yolact_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'yolact_ros': ['/home/kamba/catkin_ws/src/yolact_ros/yolact_ros/msg', '/home/kamba/catkin_ws/devel/share/yolact_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::SegmentationResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::SegmentationResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::SegmentationResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d543f9c9ec050563814d51c52fe7fbc5";
  }

  static const char* value(const ::yolact_ros::SegmentationResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd543f9c9ec050563ULL;
  static const uint64_t static_value2 = 0x814d51c52fe7fbc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros/SegmentationResult";
  }

  static const char* value(const ::yolact_ros::SegmentationResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Result definition\n\
yolact_ros/Segments segments\n\
int32 id\n\
\n\
\n\
================================================================================\n\
MSG: yolact_ros/Segments\n\
Header header\n\
Header image_header\n\
Segment[] segments\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: yolact_ros/Segment\n\
string Class\n\
float64 probability\n\
int32 xmin\n\
int32 ymin\n\
int32 xmax\n\
int32 ymax\n\
int32[] x_masks\n\
int32[] y_masks\n\
";
  }

  static const char* value(const ::yolact_ros::SegmentationResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segments);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SegmentationResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros::SegmentationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros::SegmentationResult_<ContainerAllocator>& v)
  {
    s << indent << "segments: ";
    s << std::endl;
    Printer< ::yolact_ros::Segments_<ContainerAllocator> >::stream(s, indent + "  ", v.segments);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MESSAGE_SEGMENTATIONRESULT_H
