// Generated by gencpp from file yolact_ros/Segments.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MESSAGE_SEGMENTS_H
#define YOLACT_ROS_MESSAGE_SEGMENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <yolact_ros/Segment.h>

namespace yolact_ros
{
template <class ContainerAllocator>
struct Segments_
{
  typedef Segments_<ContainerAllocator> Type;

  Segments_()
    : header()
    , image_header()
    , segments()  {
    }
  Segments_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , segments(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::yolact_ros::Segment_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yolact_ros::Segment_<ContainerAllocator> >::other >  _segments_type;
  _segments_type segments;





  typedef boost::shared_ptr< ::yolact_ros::Segments_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros::Segments_<ContainerAllocator> const> ConstPtr;

}; // struct Segments_

typedef ::yolact_ros::Segments_<std::allocator<void> > Segments;

typedef boost::shared_ptr< ::yolact_ros::Segments > SegmentsPtr;
typedef boost::shared_ptr< ::yolact_ros::Segments const> SegmentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros::Segments_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros::Segments_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yolact_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'yolact_ros': ['/home/kamba/catkin_ws/src/yolact_ros/yolact_ros/msg', '/home/kamba/catkin_ws/devel/share/yolact_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::Segments_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros::Segments_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::Segments_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros::Segments_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::Segments_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros::Segments_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b0937284d770b93e976b3fece0798c2";
  }

  static const char* value(const ::yolact_ros::Segments_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b0937284d770b93ULL;
  static const uint64_t static_value2 = 0xe976b3fece0798c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros/Segments";
  }

  static const char* value(const ::yolact_ros::Segments_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros::Segments_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Header image_header\n\
Segment[] segments\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: yolact_ros/Segment\n\
string Class\n\
float64 probability\n\
int32 xmin\n\
int32 ymin\n\
int32 xmax\n\
int32 ymax\n\
int32[] x_masks\n\
int32[] y_masks\n\
";
  }

  static const char* value(const ::yolact_ros::Segments_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros::Segments_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.segments);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Segments_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros::Segments_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros::Segments_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "segments[]" << std::endl;
    for (size_t i = 0; i < v.segments.size(); ++i)
    {
      s << indent << "  segments[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolact_ros::Segment_<ContainerAllocator> >::stream(s, indent + "    ", v.segments[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MESSAGE_SEGMENTS_H
