sciurus17:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - waist_yaw_joint
      - l_arm_joint1
      - l_arm_joint2
      - l_arm_joint3
      - l_arm_joint4
      - l_arm_joint5
      - l_arm_joint6
      - l_arm_joint7
      - l_hand_joint
      - neck_yaw_joint
      - neck_pitch_joint
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7
      - r_hand_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    []