(cl:defpackage yolact_ros-msg
  (:use )
  (:export
   "<SEGMENT>"
   "SEGMENT"
   "<SEGMENTATIONACTION>"
   "SEGMENTATIONACTION"
   "<SEGMENTATIONACTIONFEEDBACK>"
   "SEGMENTATIONACTIONFEEDBACK"
   "<SEGMENTATIONACTIONGOAL>"
   "SEGMENTATIONACTIONGOAL"
   "<SEGMENTATIONACTIONRESULT>"
   "SEGMENTATIONACTIONRESULT"
   "<SEGMENTATIONFEEDBACK>"
   "SEGMENTATIONFEEDBACK"
   "<SEGMENTATIONGOAL>"
   "SEGMENTATIONGOAL"
   "<SEGMENTATIONRESULT>"
   "SEGMENTATIONRESULT"
   "<SEGMENTS>"
   "SEGMENTS"
  ))

