; Auto-generated. Do not edit!


(cl:in-package yolact_ros-msg)


;//! \htmlinclude SegmentationResult.msg.html

(cl:defclass <SegmentationResult> (roslisp-msg-protocol:ros-message)
  ((segments
    :reader segments
    :initarg :segments
    :type yolact_ros-msg:Segments
    :initform (cl:make-instance 'yolact_ros-msg:Segments))
   (id
    :reader id
    :initarg :id
    :type cl:integer
    :initform 0))
)

(cl:defclass SegmentationResult (<SegmentationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SegmentationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SegmentationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name yolact_ros-msg:<SegmentationResult> is deprecated: use yolact_ros-msg:SegmentationResult instead.")))

(cl:ensure-generic-function 'segments-val :lambda-list '(m))
(cl:defmethod segments-val ((m <SegmentationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yolact_ros-msg:segments-val is deprecated.  Use yolact_ros-msg:segments instead.")
  (segments m))

(cl:ensure-generic-function 'id-val :lambda-list '(m))
(cl:defmethod id-val ((m <SegmentationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader yolact_ros-msg:id-val is deprecated.  Use yolact_ros-msg:id instead.")
  (id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SegmentationResult>) ostream)
  "Serializes a message object of type '<SegmentationResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'segments) ostream)
  (cl:let* ((signed (cl:slot-value msg 'id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SegmentationResult>) istream)
  "Deserializes a message object of type '<SegmentationResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'segments) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'id) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SegmentationResult>)))
  "Returns string type for a message object of type '<SegmentationResult>"
  "yolact_ros/SegmentationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SegmentationResult)))
  "Returns string type for a message object of type 'SegmentationResult"
  "yolact_ros/SegmentationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SegmentationResult>)))
  "Returns md5sum for a message object of type '<SegmentationResult>"
  "d543f9c9ec050563814d51c52fe7fbc5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SegmentationResult)))
  "Returns md5sum for a message object of type 'SegmentationResult"
  "d543f9c9ec050563814d51c52fe7fbc5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SegmentationResult>)))
  "Returns full string definition for message of type '<SegmentationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%yolact_ros/Segments segments~%int32 id~%~%~%================================================================================~%MSG: yolact_ros/Segments~%Header header~%Header image_header~%Segment[] segments~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: yolact_ros/Segment~%string Class~%float64 probability~%int32 xmin~%int32 ymin~%int32 xmax~%int32 ymax~%int32[] x_masks~%int32[] y_masks~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SegmentationResult)))
  "Returns full string definition for message of type 'SegmentationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result definition~%yolact_ros/Segments segments~%int32 id~%~%~%================================================================================~%MSG: yolact_ros/Segments~%Header header~%Header image_header~%Segment[] segments~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: yolact_ros/Segment~%string Class~%float64 probability~%int32 xmin~%int32 ymin~%int32 xmax~%int32 ymax~%int32[] x_masks~%int32[] y_masks~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SegmentationResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'segments))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SegmentationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SegmentationResult
    (cl:cons ':segments (segments msg))
    (cl:cons ':id (id msg))
))
